/***********************************************************************************************************
 *
 * Module : UltraSonic
 *
 * File name : ultrasonic.h
 *
 * Description : Header file for UltraSonic driver
 *
 * Author: BASSANT AHMED
 *
 ************************************************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include"std_types.h"

/*************************************************************************************************************
 *                                       Global Variables                                                    *
 ************************************************************************************************************/

extern uint8 g_edgeCount ;
extern uint16 g_timeHigh ;

/************************************************************************************************************
 *                                         Definitions                                                      *
 ***********************************************************************************************************/

#define ECHO_PORT     PORT_D
#define TRIGGER_PORT  PORT_B

#define ECHO_PIN      PIN_6
#define TRIGGER_PIN   PIN_5

/**********************************************************************************************************
 *                                        Functions Prototypes                                            *
 *********************************************************************************************************/

/*
 * Description :
 * Initialize the ICU driver
 * Setup the ICU call back function
 * Setup the direction for the trigger pin as output pin and echo pin as input pin
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the UltraSonic
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);
#endif /* ULTRASONIC_H_ */
