/***********************************************************************************************************
 *
 * Module : UltraSonic
 *
 * File name : ultrasonic.h
 *
 * Description : Source file for UltraSonic driver
 *
 * Author: BASSANT AHMED
 *
 **********************************************************************************************************/

#include <util/delay.h> /* For the delay functions */
#include"gpio.h"
#include"icu.h"
#include"ultrasonic.h"

/***********************************************************************************************************
 *                                       Global Variables                                                  *
 ***********************************************************************************************************/

 uint8 g_edgeCount = 0;
 uint16 g_timeHigh = 0;

/************************************************************************************************************
 *                                        Functions Definitions                                             *
************************************************************************************************************/

/*
 * Description :
 * Initialize the ICU driver
 * Setup the ICU call back function
 * Setup the direction for the trigger pin as output pin and echo pin as input pin
 */
void Ultrasonic_init(void){

	/*Initialize the ICU driver*/
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	Icu_init(&Icu_Config);

	/*Setup the ICU call back function*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output pin and echo pin as input pin*/
	GPIO_setupPinDirection(ECHO_PORT, ECHO_PIN, INPUT_PIN);
	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, OUTPUT_PIN);


}

/*
 * Description :
 * Send the Trigger pulse to the UltraSonic
 */
void Ultrasonic_Trigger(void){

	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOW);

}

/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void){

	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();

		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();

		/*Clear the timer counter register*/
		Icu_clearTimerValue();

		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);

		g_edgeCount = 0;
	}

}

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){

	Ultrasonic_Trigger();

	/* The right number is = 58.8 but this one for more accuracy between LCD and UltraSonic at proteus
	 * Speed of sound at proteus = 346 m \ sec
	 */
	return ( g_timeHigh / 57.8) ;/*(34600 * 8.0 *  g_timeHigh) / (F_CPU * 2.0)*/

}




